learning_rate = 0.001
result_dir = './results'
noise_rate = 0.50        #corruption rate, should be less than 1
forget_rate = None
noise_type = 'symmetric' #[pairflip, symmetric]
num_gradual = 20        #how many epochs for linear drop rate, can be 5, 10, 15. This parameter is equal to Tk for R(T) in Co-teaching paper.
exponent = 1            #exponent of the forget rate, can be 0.5, 1, 2. This parameter is equal to c in Tc for R(T) in Co-teaching paper.
top_bn = True
dataset = 'cifar10'       #cifar10, cifar100
n_epoch = 500
seed = 1
print_freq = 50
num_workers = 4
num_iter_per_epoch = 468
epoch_decay_start = 80
logs_dir = './tf_logs'
batch_size = 128
saved_models_dir = './models'
save_frequency = 1